export const ADD_INGREDEIENT = "ADD_INGREDEIENT";
export const REMOVE_INGREDEIENT = "REMOVE_INGREDEIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
